version: "3.9"
services:
  stable-diffusion-telegram:
    build: .
    user: "ldm-dev:ldm-dev"
    volumes:
      - huggingface-cache:/home/ldm-dev/.cache/huggingface
      - .:/opt/ldm
      - ./optimizedSD:/opt/ldm_package/optimizedSD
    runtime: nvidia
volumes:
  huggingface-cache:
